ci:
  autoupdate_branch: "main"
  autoupdate_schedule: monthly
repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.254'
    hooks:
      - id: ruff
        files: "^training_pipeline/"
        args: [--fix, --exit-non-zero-on-fix]


  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        name: bandit
        types: [python]
        files: "^training_pipeline/"
        args: ["-f", "custom", "-q"]